server:
  port: 9494
spring:
  application:
    name: EShop-PAYMENT
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka