server:
  port: 9191

spring:
  application:
    name: eshop-admin  # ✅ This is where the service name must go
  datasource:
    url: jdbc:mysql://localhost:3306/project_micro
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

eureka:
  instance:
    prefer-ip-address: true  # ✅ Optional but recommended for localhost testing
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
